apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "billing-service.fullname" . }}
  labels:
    app: {{ include "billing-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "billing-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "billing-service.name" . }}
    spec:
      containers:
        - name: {{ include "billing-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
            - name: APP_NAME
              value: "{{ .Values.app.name }}"
            - name: APP_VERSION
              value: "{{ .Values.app.version }}"
            - name: ENVIRONMENT
              value: "{{ .Values.app.environment }}"
          