# Default values for logistics-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  image:
  repository: logisticsacr3507.azurecr.io/billing-service
  tag: 15

app:
  name: billing-service
  version: v1
  environment: dev

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

container:
  port: 5000




autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50