apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tracking-service
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: tracking-service
  namespaceSelector:
    matchNames:
      - logistics
  endpoints:
    - port: http
      path: /metrics
      interval: 10s