apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: logistics
spec:
  provider: azure
  parameters:
    keyvaultName: kv-logistics-13074
    tenantId: f56fc7e1-042e-4c06-aa0a-07ae2e7d6aad
    objects: |
      array:
        - |
          objectName: DBPASSWORD
          objectType: secret