trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  acrName: 'logisticsacr3507'
  acrLoginServer: 'logisticsacr3507.azurecr.io'
  imageTag: '$(Build.BuildId)'

stages:

- stage: BuildScanPush
  displayName: Build, Scan and Push Images
  jobs:
    - job: BuildJob
      steps:
        - checkout: self

        - script: |
            set -e

            echo "Login to Azure"
            az login \
              --service-principal \
              --username "$AZURE_CLIENT_ID" \
              --password "$AZURE_CLIENT_SECRET" \
              --tenant "$AZURE_TENANT_ID"

            echo "Login to ACR"
            az acr login --name $(acrName)

            TAG=$(Build.BuildId)
            ACR=$(acrLoginServer)

            echo "Building tracking-service"
            docker build -t $ACR/tracking-service:$TAG -f app/Dockerfile app

            echo "Building billing-service"
            docker build -t $ACR/billing-service:$TAG -f app-billing/Dockerfile app/app-billing

            echo "Building notification-service"
            docker build -t $ACR/notification-service:$TAG -f app-notification/Dockerfile app/app-notification

            echo "Running Trivy scan"
            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --exit-code 0 $ACR/tracking-service:$TAG
            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --exit-code 0 $ACR/billing-service:$TAG
            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --exit-code 0 $ACR/notification-service:$TAG

            echo "Pushing images"
            docker push $ACR/tracking-service:$TAG
            docker push $ACR/billing-service:$TAG
            docker push $ACR/notification-service:$TAG

          env:
            AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
            AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
            AZURE_TENANT_ID: $(AZURE_TENANT_ID)

- stage: UpdateGitOps
  displayName: Update Helm Values
  dependsOn: BuildScanPush
  condition: succeeded()
  jobs:
    - job: UpdateHelm
      steps:
        - checkout: self
          persistCredentials: true

        - script: |
            set -e
            TAG=$(Build.BuildId)

            sed -i "s/tag:.*/tag: $TAG/" helm/logistics-service/values.yaml
            sed -i "s/tag:.*/tag: $TAG/" helm/billing-service/values.yaml
            sed -i "s/tag:.*/tag: $TAG/" helm/notification-service/values.yaml

            git config user.email "azure-pipeline@local"
            git config user.name "azure-pipeline"

            git add helm/

            git commit -m "Update all services to $TAG [skip ci]" || echo "No changes"
            git push origin HEAD:main