{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logistics-ingress
  namespace: logistics
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
{{- range .Values.ingress.services }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .name }}
                port:
                  number: 80
{{- end }}
{{- end }}